### ISSUE TITLE
Pre-processing the sample data

### ISSUE THREAD

**Issue by rezakj** [robinmeyers/TranslocPipeline#1]
Hi, 

I ran the pre-processing script  `(TranslocPreprocess.pl)` to deconvolute the pooled libraries and trim the adapters from the sample test data. It did the first step perfectly and the reads were demultiplexd in my "~/preprocess/multx" folder but the read trimming did not work.  Here is what the log file says: 

`Pre-processing RAG1A_IR_SRep1
Running SeqPrep on RAG1A_IR_SRep1
SeqPrep -f preprocess//multx/RAG1A_IR_SRep1_R1.fq.gz -r preprocess//multx/RAG1A_IR_SRep1_R2.fq.gz -1 preprocess//trim/RAG1A_IR_SRep1_R1.fq.gz -2 preprocess//trim/RAG1A_IR_SRep1_R2.fq.gz -L 30 -A AGATCGGAAGAGCGGTTCAG -B AGATCGGAAGAGCGTCGTGT >> preprocess//logs/RAG1A_IR_SRep1.log 2>&1
Problem reading quality line for SRR1270047.161485 161485 length=251 GAGAGGGTTTCCCCTCAAAGGAATCCTTCTTTTCCTTTTGAGCTTCTTCAGGTGTCTTTTCAAAGGATCTCACCCGGAACAGCTTAAATTTCCATTCTGAAAATTTAATATGTGGGTGCTGAATTTCATCTGGGGCAGAACTGAGTCCCAAGATCCTTTCCTAATTTCTAGTGTTAGTGAAGATTTCTACCACGCGTGCCCTATAGTAGATCGGAAGAGC
Problem reading quality line for SRR1270047.161485 161485 length=251 GAGAGGGTTTCCCCTCAAAGGAATCCTTCTTTTCCTTTTGAGCTTCTTCAGGTGTCTTTTCAAAGGATCTCACCCGGAACAGCTTAAATTTCCATTCTGAAAATTTAATATGTGGGTGCTGAATTTCATCTGGGGCAGAACTGAGTCCCAAGATCCTTTCCTAATTTCTAGTGTTAGTGAAGATTTCTACCACGCGTGCCCTATAGTAGATCGGAAGAGC
Processing reads... |fastq record not beginning with @
fastq record not beginning with @
Pairs Processed:    1
Pairs Merged:   0
Pairs With Adapters:    0
Pairs Discarded:    1
CPU Time Used (Minutes):    0.000000
Finished fastq-trim on RAG1A_IR_SRep1 in 0.083147 seconds`

I ran the SeqPrep with the same parameters outside the script but got the same error. I checked the fastq records and they all start with @, and used the same metadata file provided in the sample data. Would you please help me with this. 

Thank you,
Reza

**Comment by robinmeyers** [comment]
Hi Reza,

This appears to be a problem from a recent version of SeqPrep. See: https://github.com/jstjohn/SeqPrep/issues/35

They mention that installing an older version worked for them.

Best,
Robin

**Comment by rezakj** [comment]
Hi Robin, 

Do you know which version of SeqPrep works, I tried a few older versions and commits but they all were giving me some sort of error. 

If not, do you recommend using cutadapt for removing adapters and then continue with the pipeline? 
something like:
cutadapt --quality-base=30 --minimum-length=30 --overlap=3 -a AGATCGGAAGAGCGGTTCAG -A AGATCGGAAGAGCGTCGTGT -o out1.fastq -p out2.fastq in1.fastq in2.fastq

Reza

**Comment by rezakj** [comment]
I changed the following lines in `TranslocPreprocess.pl` and it worked for me. Let me know if I am missing anything, thank you. 

From:

`System("echo \"Running SeqPrep on $expt\" >> $logfile",1);
        my $t0_trim = [gettimeofday];
        my $trim_cmd = join(" ","SeqPrep -f",$meta{$expt}->{R1},"-r",$meta{$expt}->{R2},
        "-1",$meta{$expt}->{R1trim},"-2",$meta{$expt}->{R2trim},
        "-L $minlen -A $forward_adapter -B $reverse_adapter >> $logfile 2>&1");
System("echo \"$trim_cmd\" >> $logfile",1);
System($trim_cmd,1) or croak "Error: failed running SeqPrep on $expt";`

To:

`System("echo \"Running cutadapt on $expt\" >> $logfile",1);
my $t0_trim = [gettimeofday];
my $trim_cmd = join(" ","cutadapt ",$meta{$expt}->{R1}," ",$meta{$expt}->{R2},                                                  
"-o",$meta{$expt}->{R1trim},"-p",$meta{$expt}->{R2trim},                                                    
"--minimum-length=$minlen -a $forward_adapter -A $reverse_adapter >> $logfile 2>&1");
System("echo \"$trim_cmd\" >> $logfile",1);
System($trim_cmd,1) or croak "Error: failed running cutadapt on $expt";
`

Thank you, 
Reza

**Comment by Huston-github** [comment]
Hi Reza,
I had the same error, but I solved it by reinstalling the ea-utils software on github.
$ wget https://storage.googleapis.com/google-code-archive-downloads/v2/code.google.com/ea-utils/ea-utils.1.1.2-537.tar.gz
$ tar xzvf ea-utils.1.1.2-537.tar.gz
$ PREFIX=~/local/bin make
